### ISSUE TITLE
Migrate TodoMVC Vanilla JS Elm Architecture Example to Here!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/todo-list-javascript-tutorial#5]
# Todo:

+ [x] Add example/use-case for using ***Tap*** in **`learn-tape`** for reasons described in: https://github.com/dwyl/learn-tape/issues/34 
  > + [x] Done: https://github.com/dwyl/learn-tape/pull/35
+ [x] ***Transfer*** the content of https://github.com/dwyl/learn-elm-architecture-in-javascript/blob/master/todo-list.md to _this_ repository.
  + [x] `mkdir lib`
  + [x] `git mv ./examples/todo-list/* ./lib`
  + [x] `git rm -rf ./examples/`
  + [x] Update title in `todo-list.md` to reflect new repo.
  + [x] Remove old readme: `git rm README.md` 
  + [x] `git mv todo-list.md README.md` 
+ [x] **Split** out the sections into their own _individual_ `.md` files 
**so _that_** they are more "bitesize" (_better for users_)
_and_ we can track page-view/scroll (_i.e. "completion"_) stats for the tutorial.
+ [x] **Add to**: https://github.com/snipcart/learn-vanilla-js  
  > + [x] Proposed: https://github.com/snipcart/learn-vanilla-js/issues/7
  > + [x] Positive Feedback: https://github.com/snipcart/learn-vanilla-js/issues/7#issuecomment-437420335
 ![image](https://user-images.githubusercontent.com/194400/48281929-225f7d00-e450-11e8-80b6-87eec9de0dc7.png)
  > + [x] Pull Request created: https://github.com/snipcart/learn-vanilla-js/pull/8 

+ [x] Share on **HackerNews**: https://news.ycombinator.com/item?id=18353112 `#tumbleweed` ...
+ [x] Create **Pull Request** adding the resource to **TasteJS** to help **_complete_ beginners** learn TodoMVC! GOTO: https://github.com/dwyl/todo-list-javascript-tutorial/issues/12
  > + [x] **Open issue** on https://github.com/tastejs/todomvc/issues informing community of the tutorial.
  > + [x] Issue created: https://github.com/tastejs/todomvc/issues/1950 🤞 
  > + [x] Initial _Positive_ Feedback: 
![image](https://user-images.githubusercontent.com/194400/48121913-2469e600-e26e-11e8-8ed6-8ec2c88ea876.png)

  
see reasoning in: https://github.com/nelsonic/todomvc-vanilla-javascript-elm-architecture-example/issues/1

**Comment by nelsonic** [comment]
Following this Git Merge strategy: https://stackoverflow.com/a/10548919/1148249
template:
```sh
cd path/to/project-b
git remote add project-a path/to/project-a
git fetch project-a
git merge --allow-unrelated-histories project-a/master # or whichever branch you want to merge
git remote remove project-a
```
actual:
```sh
cd /code/todomvc-vanilla-javascript-elm-architecture-example
git remote add project-a git@github.com:dwyl/learn-elm-architecture-in-javascript.git
git fetch project-a
git merge --allow-unrelated-histories project-a/master
git remote remove project-a
```
A few merge conflicts: 
![image](https://user-images.githubusercontent.com/194400/47832226-173f8980-dd8c-11e8-8007-96eb50367cb9.png)

Fixing ...

**Comment by nelsonic** [comment]
Shared the link to the Repo on Founders & Coders `main` Gitter Channel:
![image](https://user-images.githubusercontent.com/194400/47888346-f33b8100-de3b-11e8-91e2-dea2090a2b41.png)


_Read_ by _lots_ of people. 
![image](https://user-images.githubusercontent.com/194400/47888273-5aa50100-de3b-11e8-9496-67000ddeb403.png)

_One_ person from F&C showed enough of an _interest_ to "Star" the repo: Yvonne ❤️ 
![image](https://user-images.githubusercontent.com/194400/47888195-e79b8a80-de3a-11e8-8109-f4f4b2dafa85.png)
_Nobody_ bothered to reply with a comment. Everyone's _too busy_. 

If it was a tutorial on how to build a React App in 27 seconds and automatically get a job at Facebook,
it would have received instant acknowledgement ... 
But the _fundamental_ skills of building an App from Scratch following TDD & _without_ a framework ...? `#crickets` 😞 

I need to _fix_ this. 🤔

**Comment by nelsonic** [comment]
Migrated. closing. 👍
